Problem 1:-
In a cricket tournament, based on the outcome of a particular match a team gets following points:

wins gets 7 points
draws gets 2 points
losses gets 0 points
Team Aravali plays 8 matches in this tournament. It wins 4 matches, loses 3 matches and draws 1. What is the total number of points gained by the Team austria?


a) The outcome variables are defined below?
b) Calculate the total points gained by Team Austria and print.

In [1]:
wins = 4
draws = 1
losses = 3

total_points = (wins * 7) + (draws * 2) + (losses * 0)
print(f"The Total Points gained by Australia is : {total_points}")

The Total Points gained by Australia is : 30


Problem 2:-
Root of a function  f(x)  is defined as the value  x  where  f(x)=0 
Consider a quadratic function  f(x)=x2+3x−4 
Find the value of the function  f(x)  at points  x=7,x=−1,x=1 .
  a)Calculate the value of the function f(x) at x = 2.
  b) Calculate the value of the function f(x) at x = 1

In [2]:
def f(x):
    return x**2 + 3*x - 4
result_2 = f(2)
print(f"The result of f(x) at x=2 := ",result_2)
result_1 = f(1)
print(f"The result of f(x) at x=1 :- ",result_1)

The result of f(x) at x=2 :=  6
The result of f(x) at x=1 :-  0


Problem 3:-
A list contains the average daily temperature(in degree Celsius) of a city over a particular week. Write a Python code to swap the highest and the lowest temperature

a) A list containing average daily temperature over a week 
temperatures = [34, 40, 29, 33, 42, 37, 9 ]

b) The expected ot 
 


c)Store the highest eperature


d) Index of the element with the highest temperature
maxemp_index = 


e) Store the lowest temperaure 
min_temp = 

f) Index of the element with the lowest temperature
min_temp_index = 

In [3]:
temp = [34,40,29,33,42,37,9]
avg = sum(temp) / 2
print("Average is : ",avg)
maxi = max(temp)
max_index = temp.index(maxi)
print("Highest temperature is : ",maxi)
print("Highest temperature Index is : ",max_index)
mini = min(temp)
mini_index = temp.index(mini)
print("Lowest temperature is : ",mini)
print("Lowest temperature index is : ",mini_index)

Average is :  112.0
Highest temperature is :  42
Highest temperature Index is :  4
Lowest temperature is :  9
Lowest temperature index is :  6


problem 4:- Calculate the median price

a) Step 1 - Obtain the sorted list
b)Check if the number of elements in the list is even or odd
c)Use the corresponding formula to calculate the median and print the median
d) Check which is greater, mean or median

In [4]:
prices = [3,6,12,15,22,25,30]
sorted_prices = sorted(prices)
num_elements = len(sorted_prices)
if num_elements % 2 == 0:  # Even number of elements
    middle_index_1 = num_elements // 2 - 1
    middle_index_2 = num_elements // 2
    median = (sorted_prices[middle_index_1] + sorted_prices[middle_index_2]) / 2
else: 
    middle_index = num_elements // 2
    median = sorted_prices[middle_index]
print("Median price:", median)

# Calculate the mean
mean = sum(prices) / len(prices)
print("Given Data Mean is : ",format(mean,'.2f'))
if mean > median:
    print("Mean is greater than median.")
elif median > mean:
    print("Median is greater than mean.")
else:
    print("Mean and median are equal.")


Median price: 15
Given Data Mean is :  16.14
Mean is greater than median.


Problem 5:- 
Having a nested list sometimes might be a bit problematic. An individual was asked to collect the names of companies in the technology sector.
 While creating the list, by mistake the last three companies were subsumed in a list as shown below. You are required to get rid of the nesting

a)The list of tech companies curated by the individual
tech_companies = ['Qualcomm','Google','Apple',['Nvidia','Cisco','Samsung']]

In [5]:
tech = ['Qualcomm','Google','Apple',['Nvidia','Cisco','Samsung']]
def flatten_list(nested_list):
    flattened_list = []
    for item in nested_list:
        if isinstance(item,list):
            flattened_list.extend(flatten_list(item))
        else:
            flattened_list.append(item)
    return flattened_list
flattened_tech_companies = flatten_list(tech)
print(flattened_tech_companies)

['Qualcomm', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']


Problem 6:-
Another measure of average
Mode is defined as the value that appears most often in a set of data values. Mode corresponds to the most frequent value.
You are given a list of numbers and you need to calculate the mode of this list.

 A list containing average daily temperature over 10 days
temperatures = [34, 40, 29, 33, 42, 40, 39, 34, 34,33 ]

In [6]:
import statistics
temperatures = [34, 40, 29, 33, 42, 40, 39, 34, 34, 33]
mode_temperature = statistics.mode(temperatures)
print("Mode of temperatures:", mode_temperature)

Mode of temperatures: 34


Problem 7:-  numpy
Construct a 2-D  10∗10  matrix with the following constraints:
The element at  [0,0]  should be 1
The element at  [0,9]  should be 100
The element at  [9,0]  should be 50
The interval between elements in rows should be constant
The interval between elements in columns should be constant

In [7]:
import numpy as np
matrix = np.zeros((10,10))
matrix[0,0] = 1
matrix[0,9] = 100
matrix[9,0] = 50
row_interval = (100-1)/(10-1)
col_interval = (50-1) /(10-1)
for i in range(1, 10):
    matrix[0, i] = int(matrix[0, i - 1] + row_interval)
    matrix[i, 0] = int(matrix[i - 1, 0] + col_interval)
print(matrix)

[[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  6.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 11.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 16.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 21.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 26.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 31.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 36.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 41.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 46.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


Problem 8:- numpy
Construct a list of first 100 natural numbers.Create a two dimensional array with 10 rows and whose each row contains 10 columns and each number in this array is the square of the number from your constructed list.
For example : [[1,4,9,...,100],[121,144,...],......,]

In [8]:
numbers = np.arange(1, 101)
matrix = numbers.reshape(10, 10)
squared_matrix = matrix ** 2
print(squared_matrix)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
